[tool.poetry]
name = "labeler"
version = "0.1.0"
description = "Easily create PDF documents for printing on label paper"
authors = ["Luke Shiner <luke@lukeshiner.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/lukeshiner/labeler"
repository = "https://github.com/lukeshiner/labeler"

classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Topic :: Utilities",
    "Topic :: Other/Nonlisted Topic",
]

[tool.coverage.run]
branch = true
omit = ["tests/*",]

[tool.poetry.dependencies]
python = "^3.6"
reportlab = "^3.5.34"
pylabels = "^1.2.1"


[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
tox = "^3.14.3"
flake8 = "^3.7.9"
flake8-docstrings = "^1.5.0"
black = "^19.10b0"
pytest-cov = "^2.8.1"
coveralls = "^1.10.0"
isort = "^4.3.21"


[build-system]
requires = ["poetry>=0.12",]
build-backend = "poetry.masonry.api"

